---
- name: My First playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install package
    package:
        name: httpd
        state: installed

  - name: Install Telnet
    package:
      name: telnet
      state: installed
  
  - name: Add Bob
    package:
      name: bob
      state: absent

  - name: Add Tom
    package:
      name: tom
      state: present